### ISSUE TITLE
柏.rbの缶バッジつくりたい！

### ISSUE THREAD

**Issue by tomitahisaki** [kashiwarb-meetup/monthly-meetup#39]
https://x.com/Kirika_K2/status/1816095747663909274

柏.rbの缶バッジを作りたい！
[缶バッジ作成(pixivFACTORY)](https://factory.pixiv.net/products/can_badge)

**Comment by kozy4324** [comment]
12個以上作るなら、30個作ってしまった方が安くて笑っている
![image](https://github.com/user-attachments/assets/6076ac8f-534c-41f5-9e82-8d58ad82d2a5)

**Comment by kozy4324** [comment]
デザイン
![image](https://github.com/user-attachments/assets/5628f3a1-9450-48c1-ad56-f927be0ac822)

**Comment by kozy4324** [comment]
配送料入れて、単価100円やな
<img width="319" alt="image" src="https://github.com/user-attachments/assets/79e0e4a7-7064-4f39-add7-c0a3e955336c">

**Comment by kozy4324** [comment]
というわけで勢いでポチりました！勢い大事！

**Comment by kozy4324** [comment]
1つ100円でお譲りします（儲けはない）
